set_languages("c++20")
add_requires("vcpkg::fmt", { alias = "fmt" })
add_requires("vcpkg::cli", { alias = "cli" })
add_requires("vcpkg::cpprestsdk", { alias = "cpprestsdk" })
add_requires("vcpkg::openssl", { alias = "openssl" })

target("trkt")
set_kind("binary")
add_files("src/*.cpp")
add_packages("fmt", "cli", "cpprestsdk", "openssl")
